replicaCount: 1
image:
  repository: bluezd/suse-demo-list-projects
  pullPolicy: Always
  tag: a32e4a68b86fdf8576a4e4e2068b9a4ce132cc4e
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  annotations: {}
  name: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 8001
ingress:
  enabled: true
  annotations: {}
  hosts:
  - host: backend.suse.demo
    paths:
    - /
  tls: []
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
